# Generated by Django 2.2.5 on 2020-06-26 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200626_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='eamil_verified',
            new_name='email_verified',
        ),
    ]
