# Generated by Django 2.2.5 on 2020-06-27 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_login_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='login_method',
        ),
    ]
